version: '3'
services:
  influxdb:
    image: ddis.rosenergoatom.ru/influxdb:1.8.10
    container_name: influxdb
    hostname: influxdb
    restart: always
    ports:
      - 8086:8086
    environment:
      - INFLUXDB_DB=system
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./influxdb/db:/var/lib/influxdb
      - ./backups/influxdb:/var/backups/influxdb

  telegraf:
    image: ddis.rosenergoatom.ru/telegraf
    container_name: telegraf
#    network_mode: "host"
    hostname: koryuchkin-iv-n  # будет в графане в списке серверов
    restart: always
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
#      - FS_FOR_MONITORING=/db
    volumes:
    - /run/docker.sock:/run/docker.sock
    - ./telegraf/etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    - ./telegraf/etc/telegraf.d/:/etc/telegraf/telegraf.d/:ro
    - /:/hostfs:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
    - '127.0.0.1:8125:8125/udp'
    command: telegraf --config-directory "/etc/telegraf/telegraf.d"

  grafana:
    image: ddis.rosenergoatom.ru/grafana:10.0.1
    container_name: grafana
    hostname: grafana
    restart: always
    user: '472'
    ports:
      - 3000:3000
    environment:
#      - GF_SMTP_ENABLED=true
#      - GF_SMTP_HOST=fe-ex-ferg.rosenergoatom.ru:25
#      - GF_SMTP_FROM_ADDRESS=monitor@ddis.rosenergoatom.ru
#      - GF_SMTP_FROM_NAME=Grafana Monitor
      - DS_INFLUXDB_TELEGRAF=InfluxDB_metrics1
      - GF_SERVER_ROOT_URL=http://127.0.0.1:3000/
# ldap
#      - GF_AUTH_BASIC_ENABLED=true
#      - GF_SECURITY_ADMIN_USER=admin
#      - GF_SECURITY_ADMIN_PASSWORD__FILE=/etc/grafana/admin_password
#      - GF_AUTH_LDAP_ENABLED=true
#      - GF_AUTH_LDAP_CONFIG_FILE=/etc/grafana/ldap.toml
#      - GF_AUTH_LDAP_ALLOW_SIGN_UP=true
# end ldap
#      - GF_INSTALL_PLUGINS=speakyourcode-button-panel
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=speakyourcode-button-panel
#      - GF_DASHBOARDS_JSON_PATH=/etc/grafana/dashboards
#      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards
#      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/tel.json
#       - GF_AUTH_LDAP_ENABLED=true
#       - GF_AUTH_LDAP_CONFIG_FILE=/opt/pf-grafana/ldap.toml
    volumes:
      - ./grafana/lib/:/var/lib/grafana/
      - ./grafana/dashboards/:/etc/grafana/provisioning/
      - ./grafana/emails/:/usr/share/grafana/public/emails/
#      - ./grafana/ldap/ldap.toml:/etc/grafana/ldap.toml
#      - ./grafana/ldap/admin_password:/etc/grafana/admin_password
#      - /opt/pf-grafana:/opt/pf-grafana

#      - ./grafana-etc:/etc/grafana
    depends_on:
      - influxdb
#    healthcheck:
#      test: curl --fail http://10.1.X.X:3000 || exit 1
#      interval: 60s
#      retries: 5
#      start_period: 20s
#      timeout: 10s
#    healthcheck:
#      test: wget --no-verbose --tries=1 --spider http://localhost || exit 1
#      interval: 60s
#      retries: 5
#      start_period: 20s
#      timeout: 10s



  portainer:
    image: ddis.rosenergoatom.ru/portainer-ce:latest
    container_name: portainer
    restart: always
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer:/data
    ports:
      - 9000:9000


